version: '3.2'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./app:/app:cached
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/volumes:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=phx_app_dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PORT=3306
