version: '3.2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: rails s
    environment:
      - RAILS_ENV=development
    volumes:
      - ./app:/app:cached
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/volumes:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=rails_app_development
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PORT=3306
